listen: "0.0.0.0"
port: 8080
domain: "http://localhost:8080"
request_timeout: "5s"
global_rate_limit_key: "turl_rate_limit"
global_write_rate: 100
global_write_burst: 200
stand_alone_read_rate: 10000
stand_alone_read_burst: 500
log:
  writers: ["console", "file"]
  level: "info"
  format: "text"
  file_config:
    filepath: "/var/log/turl.log"
    max_size: 100
    max_age: 7
    max_backups: 3
tddl:
  start_num: 700000000
  step: 1000
  seq_name: "turl"
mysql:
  dsn: "root:test123@tcp(mysql:3306)/turl?charset=utf8mb4&parseTime=True&loc=Local"
cache:
  redis:
    addr: ["redis:6379"]
    dial_timeout: "5s"
  remote_cache_ttl: 1800s
  local_cache:
    ttl: 600s
    capacity: 1000000
    max_memory: 512