services:
  turl:
    image: beihai0xff/turl:latest
    hostname: turl
    container_name: turl
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command: "-f /app/config.yaml"
    volumes:
      - ./config.yaml:/app/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
  turl-ro:
    image: beihai0xff/turl:latest
    hostname: turl-ro
    container_name: turl-ro
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    command: "-f /app/config.yaml --readonly"
    volumes:
      - ./config.yaml:/app/config.yaml
    ports:
      - "80:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: turl
      MYSQL_ROOT_PASSWORD: test123
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 10s
      retries: 5
      interval: 3s

  redis:
    image: redis/redis-stack-server:7.2.0-v11
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: ["redis-server" , "--protected-mode", "no"]
    environment:
      - REDIS_ARGS="--save 10 1 --appendonly yes"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5
      interval: 3s