name: turl-ci
on:
  push:
    tags:
      - v*
      - main
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
jobs:
  lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'
          check-latest: true
          cache-dependency-path: |
            ./go.sum
      - name: Download Go Module
        run: make bootstrap
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  test:
    name: Unittest
    strategy:
      matrix:
        go-version: [ 1.21.x, 1.22.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Run Unittest
        run: make test

#  build_docker_image:
#    name: Build And Push Docker Image
#    needs: [ lint, test ]
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v4
#        # see https://github.com/actions/checkout/issues/1471
#        with:
#          fetch-depth: 0
#          filter: tree:0
#
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Build Docker Image
#        run: make build/docker BUILD_PLATFORMS=linux/amd64
